export interface FeatureFlagDefinition {
  key: string;
  label: string;
  description: string;
  descriptionI18nKey: string;
  category: "security" | "network" | "policies" | "runtime" | "cli" | "health";
  defaultValue: string;
  type: "boolean" | "enum";
  enumValues?: string[];
  requiresRestart: boolean;
  warningLevel?: "info" | "caution" | "danger";
}

export const FEATURE_FLAG_DEFINITIONS: FeatureFlagDefinition[] = [
  // ──────────────── Security (6) ────────────────
  {
    key: "REQUIRE_API_KEY",
    label: "Require API Key",
    description: "Require an API key for all incoming requests",
    descriptionI18nKey: "featureFlagRequireApiKeyDescription",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "caution",
  },
  {
    key: "INPUT_SANITIZER_ENABLED",
    label: "Input Sanitizer",
    description: "Enable input sanitization for all requests",
    descriptionI18nKey: "featureFlagInputSanitizerEnabledDescription",
    category: "security",
    defaultValue: "true",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "INJECTION_GUARD_MODE",
    label: "Injection Guard Mode",
    description: "Set the prompt injection guard mode",
    descriptionI18nKey: "featureFlagInjectionGuardModeDescription",
    category: "security",
    defaultValue: "off",
    type: "enum",
    enumValues: ["off", "warn", "block", "redact"],
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "PII_REDACTION_ENABLED",
    label: "PII Redaction",
    description: "Redact personally identifiable information from requests",
    descriptionI18nKey: "featureFlagPiiRedactionEnabledDescription",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "PII_RESPONSE_SANITIZATION",
    label: "PII Response Sanitization",
    description: "Sanitize PII from provider responses",
    descriptionI18nKey: "featureFlagPiiResponseSanitizationDescription",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "OUTBOUND_SSRF_GUARD_ENABLED",
    label: "SSRF Guard",
    description: "Block outbound requests to private/internal IP ranges",
    descriptionI18nKey: "featureFlagOutboundSsrfGuardEnabledDescription",
    category: "security",
    defaultValue: "true",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },

  // ──────────────── Network (5) ────────────────
  {
    key: "ENABLE_TLS_FINGERPRINT",
    label: "TLS Fingerprint",
    description: "Enable TLS fingerprint stealth mode",
    descriptionI18nKey: "featureFlagEnableTlsFingerprintDescription",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },
  {
    key: "ONEPROXY_ENABLED",
    label: "OneProxy Enabled",
    description: "Enable 1proxy request proxying.",
    descriptionI18nKey: "settings.featureFlags.oneproxyEnabled",
    category: "network",
    defaultValue: "true",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "MITM_DISABLE_TLS_VERIFY",
    label: "Disable TLS Verify (MITM)",
    description: "Disable TLS certificate verification for MITM proxy",
    descriptionI18nKey: "featureFlagMitmDisableTlsVerifyDescription",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "danger",
  },
  {
    key: "OMNIROUTE_ALLOW_PRIVATE_PROVIDER_URLS",
    label: "Allow Private Provider URLs",
    description: "Allow provider URLs pointing to private/internal networks",
    descriptionI18nKey: "featureFlagOmnirouteAllowPrivateProviderUrlsDescription",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
  {
    key: "ENABLE_CC_COMPATIBLE_PROVIDER",
    label: "CC Compatible Provider",
    description: "Enable Claude Code compatible provider mode",
    descriptionI18nKey: "featureFlagEnableCcCompatibleProviderDescription",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },

  // ──────────────── Policies (3) ────────────────
  {
    key: "TOOL_POLICY_MODE",
    label: "Tool Policy Mode",
    description: "Set the tool use policy enforcement mode",
    descriptionI18nKey: "featureFlagToolPolicyModeDescription",
    category: "policies",
    defaultValue: "disabled",
    type: "enum",
    enumValues: ["disabled", "warn", "block"],
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "RATE_LIMIT_AUTO_ENABLE",
    label: "Rate Limit Auto-Enable",
    description: "Automatically enable rate limiting based on usage patterns",
    descriptionI18nKey: "featureFlagRateLimitAutoEnableDescription",
    category: "policies",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "ALLOW_MULTI_CONNECTIONS_PER_COMPAT_NODE",
    label: "Multi Connections per Compat Node",
    description: "Allow multiple connections per compatibility node",
    descriptionI18nKey: "featureFlagAllowMultiConnectionsPerCompatNodeDescription",
    category: "policies",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },

  // ──────────────── Runtime (5) ────────────────
  {
    key: "OMNIROUTE_MCP_ENFORCE_SCOPES",
    label: "MCP Enforce Scopes",
    description: "Enforce scope restrictions on MCP tool access",
    descriptionI18nKey: "featureFlagOmnirouteMcpEnforceScopesDescription",
    category: "runtime",
    defaultValue: "true",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
  {
    key: "OMNIROUTE_MCP_COMPRESS_DESCRIPTIONS",
    label: "MCP Compress Descriptions",
    description: "Compress MCP tool descriptions to reduce token usage",
    descriptionI18nKey: "featureFlagOmnirouteMcpCompressDescriptionsDescription",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "OMNIROUTE_ENABLE_RUNTIME_BACKGROUND_TASKS",
    label: "Runtime Background Tasks",
    description: "Enable background task processing at runtime",
    descriptionI18nKey: "featureFlagOmnirouteEnableRuntimeBackgroundTasksDescription",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "OMNIROUTE_DISABLE_BACKGROUND_SERVICES",
    label: "Disable Background Services",
    description: "Disable all background services (quota refresh, sync, etc)",
    descriptionI18nKey: "featureFlagOmnirouteDisableBackgroundServicesDescription",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "caution",
  },
  {
    key: "OMNIROUTE_RTK_TRUST_PROJECT_FILTERS",
    label: "RTK Trust Project Filters",
    description: "Trust project-level filters from RTK without validation",
    descriptionI18nKey: "featureFlagOmnirouteRtkTrustProjectFiltersDescription",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
  {
    key: "OMNIROUTE_ENABLE_LIVE_WS",
    label: "Live Dashboard WebSocket",
    description:
      "Start the real-time dashboard WebSocket server on import (port 20129 by default).",
    descriptionI18nKey: "featureFlagOmnirouteEnableLiveWsDescription",
    category: "runtime",
    defaultValue: "true",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },

  // ──────────────── CLI (3) ────────────────
  {
    key: "CLI_COMPAT_ALL",
    label: "CLI Compat All",
    description: "Enable compatibility mode for all CLI clients",
    descriptionI18nKey: "featureFlagCliCompatAllDescription",
    category: "cli",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },
  {
    key: "MODEL_ALIAS_COMPAT_ENABLED",
    label: "Model Alias Compat",
    description: "Enable model alias compatibility layer",
    descriptionI18nKey: "featureFlagModelAliasCompatEnabledDescription",
    category: "cli",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "PRICING_SYNC_ENABLED",
    label: "Pricing Sync",
    description: "Enable automatic pricing data synchronization",
    descriptionI18nKey: "featureFlagPricingSyncEnabledDescription",
    category: "cli",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },

  // ──────────────── Health (3) ────────────────
  {
    key: "OMNIROUTE_DISABLE_LOCAL_HEALTHCHECK",
    label: "Disable Local Health Check",
    description: "Disable the local instance health check endpoint",
    descriptionI18nKey: "featureFlagOmnirouteDisableLocalHealthcheckDescription",
    category: "health",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "OMNIROUTE_DISABLE_TOKEN_HEALTHCHECK",
    label: "Disable Token Health Check",
    description: "Disable the token validation health check",
    descriptionI18nKey: "featureFlagOmnirouteDisableTokenHealthcheckDescription",
    category: "health",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "SKILLS_SANDBOX_NETWORK_ENABLED",
    label: "Skills Sandbox Network",
    description: "Enable network access in the skills sandbox environment",
    descriptionI18nKey: "featureFlagSkillsSandboxNetworkEnabledDescription",
    category: "health",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
];
